# docker-compose file for irdb
# how to use psql from this:
#
# alias psql="docker exec -it $(docker ps | grep postgres | cut -d' ' -f1) psql -U postgres"
#
# or:
#
# alias psql="docker-compose exec postgres psql -U postgres
#
# This cannot be used with commandline redirection. In that case use different flags:
# 
# echo "CREATE DATABASE companydb" | docker-compose exec -T postgres psql -U postgres
# docker-compose exec -T postgres psql -U postgres companydb < companydb.sql
#

version: "3.8"
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
 
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: info@hsleiden.nl
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "8000:80"
    volumes:
    - ./pgadmin-data:/var/lib/pgadmin
    links:
    - "postgres:postgres"

  backend:
    image: insofad_backend
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/webshopbob
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
  
  frontend:
    image: insofad_frontend
    build: .
    ports:
      - "4200:4200"
    


